version: "3.8"

services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: ambuapi
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://db:5432/ambuapi
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: admin
      KC_HOSTNAME_STRICT: "false"
      KC_HTTP_ENABLED: "true"
    ports:
      - "8080:8080"
    depends_on:
      - db

  api:
    build: .
    depends_on:
      - db
    ports:
      - "3005:3000"
    environment:
      DATABASE_URL: postgres://postgres:admin@db:5432/ambuapi
      PORT: 3000
      JWT_SECRET: Ambulancia
    volumes:
      - .:/app
      - /app/node_modules
      - ./keycloak.json:/app/keycloak.json
    command: "npm start"

volumes:
  db_data:
