openapi: 3.0.0
info:
  description: "API para gestionar paramédicos, conductores, asistentes, pacientes, etc."
  version: "1.0.0"
  title: "API de Gestión de Salud"
server:
  - url: "http://localhost:3005/api"
    description: "Servidor de desarrollo"

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - bearerAuth: []

tags:
  - name: "auth"
    description: "Operaciones de autenticación y autorización"
  - name: "paramedics"
    description: "Operaciones de paramédicos"
  - name: "assistants"
    description: "Operaciones de asistentes"
  - name: "ambulance"
    description: "Operaciones de ambulancias"

  - name: "user"
    description: "Operaciones del usuario"
 
  - name: "Patient"
    description: "Operaciones de pacientes"

paths:
  /api/auth/login:
    post:
      tags:
        - auth
      summary: Iniciar sesión / Login
      description: Autentica a un usuario con su documento y contraseña y devuelve un token JWT.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - document
                - password
              properties:
                document:
                  type: string
                  example: "1234123412"
                password:
                  type: string
                  example: "a123456789"
      responses:
        200:
          description: "Inicio de sesión exitoso"
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        401:
          description: "Credenciales inválidas"
        500:
          description: "Error interno del servidor"

  /api/admin/paramedic:
    post:
      tags:
        - paramedics
      summary: Crear un nuevo paramédico
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ParamedicInput"
      responses:
        "201":
          description: Paramedic created successfully
        "400":
          description: Validation error
        "403":
          description: Access Denied
        "500":
          description: Internal server error
  /api/admin/paramedic:
    get:
      tags:
        - paramedics
      summary: Obtener todos los paramédicos
      responses:
        "200":
          description: Lista de paramédicos
        "403":
          description: Access Denied
        "500":
          description: Internal server error

  /admin/paramedic/{id}:
    get:
      tags:
        - paramedics
      summary: Obtener paramédico por ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Información del paramédico
        "403":
          description: Access Denied
        "500":
          description: Internal server error
    put:
      tags:
        - paramedics
      summary: Modificar paramédico
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ParamedicInput"
      responses:
        "200":
          description: Paramedic updated successfully
        "403":
          description: Access Denied
        "500":
          description: Internal server error
    delete:
      tags:
        - paramedics
      summary: Eliminar paramédico
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "204":
          description: Paramedic deleted
        "403":
          description: Access Denied
        "500":
          description: Internal server error

  /api/admin/assistant/add:
    post:
      tags:
        - assistants
      summary: Crear un nuevo asistente
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AssistantInput"
      responses:
        "201":
          description: Assistant created successfully
        "400":
          description: Validation error
        "403":
          description: Access Denied
        "500":
          description: Internal server error

  /api/admin/assistant:
    get:
      tags:
        - assistants
      summary: Obtener todos los asistentes
      responses:
        "200":
          description: Lista de asistentes
        "403":
          description: Access Denied
        "500":
          description: Internal server error

  /api/admin/assistants/{id}:
    get:
      tags:
        - assistants
      summary: Obtener asistente por ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Información del asistente
        "403":
          description: Access Denied
        "500":
          description: Internal server error
    put:
      tags:
        - assistants
      summary: Modificar asistente
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AssistantInput"
      responses:
        "200":
          description: Assistant updated successfully
        "403":
          description: Access Denied
        "500":
          description: Internal server error
    delete:
      tags:
        - assistants
      summary: Eliminar asistente
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "204":
          description: Assistant deleted
        "403":
          description: Access Denied
        "500":
          description: Internal server error

  /api/admin/ambulance/add:
    post:
      tags:
        - Ambulances
      summary: Create a new ambulance
      description: Crea una nueva ambulancia. Solo accesible por usuarios con rol ADMIN.
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                modelo:
                  type: string
                  example: "Toyota Hiace"
                placa:
                  type: string
                  example: "ABC-123"
                tipo:
                  type: string
                  example: "UCI"
                ipsId:
                  type: integer
                  example: 1
      responses:
        '201':
          description: Ambulancia creada exitosamente.
        '400':
          description: Error de validación.
        '403':
          description: Acceso denegado.
        '500':
          description: Error interno del servidor.

  /api/admin/ambulance:
    get:
      tags:
        - Ambulances
      summary: Get all ambulances
      description: Retorna todas las ambulancias registradas. Solo accesible por ADMIN.
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Lista de ambulancias.
        '403':
          description: Acceso denegado.
        '500':
          description: Error interno del servidor.

  api/admin/ambulance/{id}:
    get:
      tags:
        - Ambulances
      summary: Get ambulance by ID
      description: Obtiene una ambulancia específica por su ID. Solo accesible por ADMIN.
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Ambulancia encontrada.
        '403':
          description: Acceso denegado.
        '500':
          description: Error interno del servidor.

    delete:
      tags:
        - Ambulances
      summary: Delete ambulance by ID
      description: Elimina una ambulancia por su ID. Solo accesible por ADMIN.
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Ambulancia eliminada exitosamente.
        '403':
          description: Acceso denegado.
        '500':
          description: Error interno del servidor.

    put:
      tags:
        - Ambulances
      summary: Update ambulance by ID
      description: Modifica los datos de una ambulancia. Solo accesible por ADMIN.
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                modelo:
                  type: string
                  example: "Mercedes Sprinter"
                placa:
                  type: string
                  example: "XYZ-789"
                tipo:
                  type: string
                  example: "Básica"
                ipsId:
                  type: integer
                  example: 2
      responses:
        '200':
          description: Ambulancia actualizada correctamente.
        '400':
          description: Error de validación.
        '403':
          description: Acceso denegado.
        '500':
          description: Error interno del servidor.
